package credential_assignments

var sourceCodeFileExtensions = map[string]struct{}{
	".go":    {},
	".php":   {},
	".c":     {},
	".cs":    {},
	".java":  {},
	".rb":    {},
	".swift": {},
	".py":    {},
	".kt":    {},
	".rs":    {},
	".r":     {},
	".scala": {},
	".hs":    {},
	".pl":    {},
	".lua":   {},
	".cpp":   {},
	".ts":    {},
	".tsx":   {},
	".js":    {},
	".jsx":   {},
	".ps1":   {},
}
